import React,{useState} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';
const tokens=[
{name:'MoonBolt',symbol:'MOONB',mcap:'$2.4M',vol:'$420K',age:'4m',score:92,safety:78,stage:'EARLY',trend:'+18.4%',liq:'$220K',dex:'Uniswap V3'},
{name:'SwiftCat',symbol:'SWCAT',mcap:'$3.1M',vol:'$520K',age:'9m',score:85,safety:70,stage:'GROWING',trend:'+14.2%',liq:'$310K',dex:'Ramses V3'},
{name:'RocketDog',symbol:'RDOG',mcap:'$1.7M',vol:'$280K',age:'13m',score:81,safety:66,stage:'RUNNING',trend:'+24.8%',liq:'$220K',dex:'Pons V2'},
{name:'AlphaMind',symbol:'ALPHA',mcap:'$2.1M',vol:'$390K',age:'18m',score:79,safety:73,stage:'PULLBACK',trend:'+9.7%',liq:'$190K',dex:'Uniswap V4'},
{name:'GreenFuel',symbol:'GFUEL',mcap:'$2.8M',vol:'$540K',age:'24m',score:76,safety:81,stage:'GROWING',trend:'+12.1%',liq:'$340K',dex:'Up V3'},
{name:'TurboMoon',symbol:'TURBO',mcap:'$1.4M',vol:'$260K',age:'29m',score:72,safety:69,stage:'EARLY',trend:'+8.9%',liq:'$160K',dex:'Pons V2'}];
const Icon=({children})=><span className="icon">{children}</span>;
function App(){const[tab,setTab]=useState('EARLY'),[page,setPage]=useState('radar'),[selected,setSelected]=useState(null),[favorites,setFavorites]=useState([]),[query,setQuery]=useState(''),[notice,setNotice]=useState('');
const filtered=tokens.filter(t=>t.stage===tab),toggleFav=s=>setFavorites(f=>f.includes(s)?f.filter(x=>x!==s):[...f,s]);
const open=t=>{setSelected(t);setPage('detail')}; const analyze=()=>{if(!query.trim())return;setNotice('Token analysis ready');setTimeout(()=>setNotice(''),1800)};
return <div className="app"><header className="topbar"><button className="brand" onClick={()=>setPage('radar')}><div className="panther">◢</div><div><b>RUNNER<span>HUNTER</span></b><small>FIND · TRACK · ANALYZE</small></div></button><div className="live"><i/> RADAR LIVE <small>Chain 4663</small></div></header>{notice&&<div className="toast">{notice}</div>}<main>
{page==='radar'&&<><section className="hero"><div><p className="eyebrow">ROBINHOOD CHAIN</p><h1>Find the next runner.</h1><p className="muted">Live discovery of organic momentum across the chain.</p></div><div className="heroStats"><strong>LIVE</strong><span>Last update 6s ago</span><span>Scan cycle 28s</span></div></section><div className="metrics"><div><b>{tokens.length}</b><span>Active candidates</span></div><div><b>4663</b><span>Chain ID</span></div><div><b>{favorites.length}</b><span>Favorites</span></div><div><b>0</b><span>Errors</span></div></div><nav className="tabs">{['EARLY','GROWING','RUNNING','PULLBACK'].map(x=><button className={tab===x?'active':''} onClick={()=>setTab(x)} key={x}>{x}</button>)}</nav><section className="list">{filtered.map((t,i)=><TokenRow key={t.symbol} t={t} i={i} open={open} fav={favorites.includes(t.symbol)} toggle={toggleFav}/>)}</section></>}
{page==='detail'&&selected&&<TokenDetail t={selected} back={()=>setPage('radar')} fav={favorites.includes(selected.symbol)} toggle={()=>toggleFav(selected.symbol)}/>} {page==='search'&&<Search query={query} setQuery={setQuery} analyze={analyze}/>} {page==='favorites'&&<Favorites items={tokens.filter(t=>favorites.includes(t.symbol))} open={open} toggle={toggleFav}/>} {page==='settings'&&<Settings/>}</main>
<footer><button className={page==='radar'||page==='detail'?'sel':''} onClick={()=>setPage('radar')}><Icon>⌁</Icon>Radar</button><button className={page==='search'?'sel':''} onClick={()=>setPage('search')}><Icon>⌕</Icon>Search</button><button className={page==='favorites'?'sel':''} onClick={()=>setPage('favorites')}><Icon>★</Icon>Favorites</button><button className={page==='settings'?'sel':''} onClick={()=>setPage('settings')}><Icon>⚙</Icon>Settings</button></footer></div>}
function TokenRow({t,i,open,fav,toggle}){return <div className="tokenRow" onClick={()=>open(t)}><div className="rank">{i+1}</div><div className="coin">{t.symbol[0]}</div><div className="tokenName"><b>{t.name}</b><span>{t.symbol} · RH · {t.dex}</span></div><div className="numbers"><b>{t.mcap}</b><span>{t.vol} · {t.age}</span></div><div className="score">{t.score}</div><div className="trend">{t.trend}</div><button className="star" onClick={e=>{e.stopPropagation();toggle(t.symbol)}}>{fav?'★':'☆'}</button></div>}
function TokenDetail({t,back,fav,toggle}){return <section className="detail"><button className="back" onClick={back}>‹ Back</button><div className="detailHead"><div className="coin big">{t.symbol[0]}</div><div><h2>{t.name}</h2><p>{t.symbol} · Robinhood Chain · {t.dex}</p></div><button className="star bigStar" onClick={toggle}>{fav?'★':'☆'}</button></div><div className="scores"><div><span>RADAR SCORE</span><b>{t.score}</b></div><div><span>SAFETY SCORE</span><b>{t.safety}</b></div><div><span>STAGE</span><b>{t.stage}</b></div></div><div className="price"><span>Price</span><b>$0.03421</b><em>{t.trend} · 1h</em></div><div className="detailGrid"><div><span>Market Cap</span><b>{t.mcap}</b></div><div><span>Volume</span><b>{t.vol}</b></div><div><span>Liquidity</span><b>{t.liq}</b></div><div><span>Age</span><b>{t.age}</b></div></div><div className="chart"><div className="chartLine"/><span>Price & momentum</span><small>1m · 5m · 1h · 4h · 1d</small></div><div className="contract"><span>Contract</span><code>0x3a...7f2d</code><button onClick={()=>navigator.clipboard?.writeText('0x3a...7f2d')}>Copy</button></div></section>}
function Search({query,setQuery,analyze}){return <section className="searchPage"><p className="eyebrow">TOKEN INSPECTOR</p><h1>Analyze any token.</h1><p className="muted">Paste a Robinhood Chain contract, name or symbol.</p><div className="searchBox"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="0x... / token name / symbol"/><button onClick={analyze}>Analyze</button></div><div className="infoCard"><b>Same engine as Radar</b><span>Momentum, liquidity, holders, buy/sell pressure and organicity use the same scoring system.</span></div><div className="chainCard"><span>ROBINHOOD CHAIN</span><b>Chain ID 4663</b><i>● ONLINE</i></div></section>}
function Favorites({items,open,toggle}){return <section><p className="eyebrow">SAVED</p><h1>My Favorites</h1>{items.length===0?<div className="empty">No favorites yet.<br/>Tap ☆ on a runner to save it.</div>:<section className="list">{items.map((t,i)=><TokenRow key={t.symbol} t={t} i={i} open={open} fav toggle={toggle}/>)}</section>}</section>}
function Settings(){return <section className="settings"><p className="eyebrow">SYSTEM</p><h1>Settings</h1>{[['◉','Radar Diagnostics','Live status, scan cycle, resources'],['⌁','RPC Status','Robinhood Chain endpoints'],['◔','Notifications','Alerts and runner events'],['◐','Appearance','Dark premium theme'],['ⓘ','About','RunnerHunter v0.1.0']].map(x=><div className="setting" key={x[1]}><span>{x[0]}</span><div><b>{x[1]}</b><small>{x[2]}</small></div><strong>›</strong></div>)}</section>}
createRoot(document.getElementById('root')).render(<App/>);
